// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service/service.proto

package terry_user_srv_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Input struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Input) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Output struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{1}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Output) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{5}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{6}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{7}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{8}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Input)(nil), "terry.user.srv.service.Input")
	proto.RegisterType((*Output)(nil), "terry.user.srv.service.Output")
	proto.RegisterType((*Message)(nil), "terry.user.srv.service.Message")
	proto.RegisterType((*Request)(nil), "terry.user.srv.service.Request")
	proto.RegisterType((*Response)(nil), "terry.user.srv.service.Response")
	proto.RegisterType((*StreamingRequest)(nil), "terry.user.srv.service.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "terry.user.srv.service.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "terry.user.srv.service.Ping")
	proto.RegisterType((*Pong)(nil), "terry.user.srv.service.Pong")
}

func init() { proto.RegisterFile("proto/service/service.proto", fileDescriptor_a34e2f8c9a3669d2) }

var fileDescriptor_a34e2f8c9a3669d2 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6e, 0xe2, 0x30,
	0x10, 0xc6, 0xc9, 0x42, 0x02, 0x3b, 0x27, 0xd6, 0x42, 0x08, 0x85, 0x3f, 0x8b, 0x7c, 0x0a, 0x97,
	0x2c, 0xda, 0x9e, 0x7a, 0xee, 0xa5, 0x55, 0xa9, 0x5a, 0x85, 0x27, 0x48, 0xc1, 0x72, 0xa3, 0x82,
	0x9d, 0x7a, 0x1c, 0x2a, 0x5e, 0xa6, 0xcf, 0x5a, 0xc5, 0x76, 0x68, 0x55, 0x61, 0xa9, 0x87, 0x9e,
	0x32, 0x93, 0xef, 0x37, 0xdf, 0x44, 0xdf, 0x28, 0x30, 0x2e, 0x95, 0xd4, 0xf2, 0x1f, 0x32, 0x75,
	0x28, 0x36, 0xac, 0x79, 0xa6, 0xe6, 0x2d, 0x19, 0x6a, 0xa6, 0xd4, 0x31, 0xad, 0x90, 0xa9, 0x14,
	0xd5, 0x21, 0x75, 0x2a, 0xbd, 0x84, 0xf0, 0x46, 0x94, 0x95, 0x26, 0x03, 0x08, 0xcb, 0x27, 0x29,
	0xd8, 0x28, 0x98, 0x07, 0xc9, 0xef, 0xcc, 0x36, 0x24, 0x86, 0x5e, 0x99, 0x23, 0xbe, 0x4a, 0xb5,
	0x1d, 0xfd, 0x32, 0xc2, 0xa9, 0xa7, 0x29, 0x44, 0xf7, 0x95, 0xae, 0x67, 0x09, 0x74, 0x36, 0x72,
	0x6b, 0x47, 0xc3, 0xcc, 0xd4, 0xa4, 0x0f, 0xed, 0x3d, 0x72, 0x37, 0x54, 0x97, 0x74, 0x0c, 0xdd,
	0x3b, 0x86, 0x98, 0x73, 0x23, 0x62, 0x7e, 0x74, 0xab, 0xea, 0x92, 0x4e, 0xa1, 0x9b, 0xb1, 0x97,
	0x8a, 0xa1, 0x71, 0x13, 0xf9, 0xbe, 0xf9, 0x10, 0x53, 0xd3, 0x09, 0xf4, 0x32, 0x86, 0xa5, 0x14,
	0x78, 0x72, 0x0e, 0x3e, 0x9c, 0x13, 0xe8, 0xaf, 0xb5, 0x62, 0xf9, 0xbe, 0x10, 0xbc, 0x71, 0x19,
	0x40, 0xb8, 0x91, 0x95, 0xd0, 0x86, 0x6b, 0x67, 0xb6, 0xa1, 0x0b, 0xf8, 0xf3, 0x89, 0x74, 0x86,
	0xe7, 0xd1, 0x19, 0x74, 0x1e, 0x0a, 0xc1, 0xc9, 0x10, 0x22, 0xd4, 0x4a, 0x3e, 0x33, 0x27, 0xbb,
	0xce, 0xe8, 0xd2, 0xaf, 0xff, 0x7f, 0x6b, 0x43, 0x77, 0x6d, 0x53, 0x26, 0xd7, 0x10, 0xae, 0x24,
	0x2f, 0x04, 0x99, 0xa6, 0xe7, 0xef, 0x90, 0x9a, 0x23, 0xc4, 0x33, 0x9f, 0x6c, 0x83, 0xa6, 0x2d,
	0x72, 0x5b, 0x07, 0xc1, 0x0b, 0xd4, 0x4c, 0xfd, 0x84, 0x59, 0xe7, 0x2a, 0xdf, 0xed, 0xc8, 0x5f,
	0x1f, 0xe9, 0xc2, 0x8c, 0xe7, 0x7e, 0xc0, 0x66, 0x48, 0x5b, 0x24, 0x87, 0xc8, 0x46, 0x4b, 0x12,
	0x1f, 0xfd, 0xf5, 0x48, 0xf1, 0xe2, 0x1b, 0x64, 0xb3, 0x60, 0x19, 0x90, 0x15, 0xf4, 0xea, 0x93,
	0x98, 0xd8, 0x27, 0xbe, 0xd1, 0x9a, 0x88, 0xfd, 0xaa, 0x14, 0x9c, 0xb6, 0x92, 0x60, 0x19, 0x3c,
	0x46, 0xe6, 0xcf, 0xb8, 0x78, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xea, 0xd4, 0x5e, 0x23, 0x38, 0x03,
	0x00, 0x00,
}
